config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Blog posts resources, generates paths for controller actions
  resources :blog_posts
  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  scope :sorted, -> { order(published_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
      <%= form.label :published_at %>
      <%= form.datetime_select :published_at, include_blank: true %>
  </div>

  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>My Blog </h1>
<% @blog_posts.each do |blog_post| %>
  <div>
    <div class="flex items-baseline space-x-4">
      <h2><%= link_to blog_post.title, blog_post %></h2>
      <% if blog_post.draft? %>
        <div class="irounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">
          Draft
        </div>
      <% end %>
      <% if blog_post.scheduled? %>
        <div class="irounded-md bg-blue-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">
          Scheduled
        </div>
      <% end %>
    </div>
    <p><%= blog_post.body%></p>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit Blog Post", edit_blog_post_path if user_signed_in? %>
<h1><%= @blog_post.title %></h1>
<div>
  <p><%= @blog_post.body %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto"> 
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
      <%= link_to "New Blog Post", new_blog_post_path %>
      <%= link_to "Profile", edit_user_registration_path %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%#= link_to "Sign up", new_user_registration_path %>
      <% end %>

    </div>

    <%= yield %>
  </body>
</html>